### ISSUE TITLE
macos build with limited localisation 

### ISSUE THREAD

**Issue by jongough** [mauroc/squiddio_pi#103]
The current build/install process for macos (osx) uses an xml file as input, buildosx/installOSX/squiddio_pi.pkgproj.in, as the base for the build. This file has 5 different language files used and these are defined statically. This file needs to have these entries built at build time to ensure all available files are used. Currently if a file is not available at build time the build will fail.

This should be the next step in the generalisation of the build files, the first step was to add the package_name at build time.

**Comment by rgleason** [comment]
We used to have to edit this file to add the auth-key, plugin name etc is it possible to have variables?
--You probably already fixed that.

**Comment by jongough** [comment]
We can add move variables to the main CMakeLists.txt that can then be used in the PluginPackage.cmake 'configure_file' process. All that needs to happen is for the variables to be added to the '.in' file and it should work. I have done the package name stuff, I presume the auth-key you are talking about is the UUID string. I can make the change for that if you want.

**Comment by rgleason** [comment]
Jon,

Here is where I think the key is.  What is it for?  
When trying to compile Tactics for MacOS I recall having to add the travis encryption of my github personal access token, somewhere in this file.

```

LIne 772

<key>PROJECT</key>
	<dict>
		<key>PROJECT_COMMENTS</key>
		<dict>
			<key>NOTES</key>
			<data>
			PCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBIVE1M
			IDQuMDEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvVFIvaHRtbDQv
			c3RyaWN0LmR0ZCI+CjxodG1sPgo8aGVhZD4KPG1ldGEgaHR0cC1l
			cXVpdj0iQ29udGVudC1UeXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7
			IGNoYXJzZXQ9VVRGLTgiPgo8bWV0YSBodHRwLWVxdWl2PSJDb250
			ZW50LVN0eWxlLVR5cGUiIGNvbnRlbnQ9InRleHQvY3NzIj4KPHRp
			dGxlPjwvdGl0bGU+CjxtZXRhIG5hbWU9IkdlbmVyYXRvciIgY29u
			dGVudD0iQ29jb2EgSFRNTCBXcml0ZXIiPgo8bWV0YSBuYW1lPSJD
			b2NvYVZlcnNpb24iIGNvbnRlbnQ9IjExMzguNTEiPgo8c3R5bGUg
			dHlwZT0idGV4dC9jc3MiPgo8L3N0eWxlPgo8L2hlYWQ+Cjxib2R5
			Pgo8L2JvZHk+CjwvaHRtbD4K
			</data>
		</dict>
		<key>PROJECT_PRESENTATION</key>
		<dict>
```

**Comment by rgleason** [comment]
I think this can be closed now.   This is pretty old.

**Comment by jongough** [comment]
I haven't been paying attention to this one. As it all seems to be working now I suspect you are correct. So I am closing int.
