### ISSUE TITLE
circleci: Pull requests are not built.

### ISSUE THREAD

**Issue by leamas** [mauroc/squiddio_pi#106]
When making a pull request, circleci does not build it: Appveyor does, though.

This is a major problem, since building the PR is the only way to make sure that it, well, builds.

It seems to be about settings in circleci (screenshot below). Here are two settings: to build PR and to pass secrets to them.

I have no possibility to test. However, if we enable the *Build forked pull requests* option it should make circleci build all PRs (?). And if we disable *Pass secrets to builds from forked pull requests*, it will not be able to upload anything. Which is what we want, I guess.

![circle-fork-setup](https://user-images.githubusercontent.com/405541/68517888-aa59ac00-0289-11ea-8c20-9e6f3e35209a.png)

**Comment by mauroc** [comment]
looks like this one can be closed. LMK if otherwise

**Comment by rgleason** [comment]
Mauroc, you can close it too, as well as Leamas.
