### ISSUE TITLE
linux: xenial: squiddio crashes when activated

### ISSUE THREAD

**Issue by leamas** [mauroc/squiddio_pi#108]
As heading says: On ubuntu/xenial   16.04 squiddio crashes when activated. A preliminary stacktrace indicates that this happens in `PlugInManager::SendCursorLatLonToAllPlugIns`

This does not happen on Windows, MacOS or flatpak. The latter is mystifying, since flatpak and ubuntu builds are pretty close.

**Comment by jongough** [comment]
Is there any intention to fix this issue? Squiddio is the 'example' plugin for the new Plugin Manger process.

**Comment by rgleason** [comment]
Reasonable question, but for me, testplugin is the one to use.

**Comment by jongough** [comment]
For testing purposes I would tend to agree that testplugin is more sensible as it is not a 'user' plugin. However, squiddio does not currently work when installed vi Plugin Manager and I would have thought it would have been the first one to work considering who was working on it.

**Comment by rgleason** [comment]
This could be tested again on Alpha channel, new push in place at meta-url   rgleason/squiddio_pi  branch: rg-alpha.

**Comment by mauroc** [comment]
looks like this one can be closed. LMK if otherwise
