### ISSUE TITLE
NDBC Bouys

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#114]
Mauro, 
I've been using rgleason/squiddio/ci  branch,  to learn more about how oesenc_pi does Plugin Management and to improve my skills and hopefully learn how to really fix some of the issues I have with the process.

In the process I've tried the new Bouy Feature. It works!  Its going to be a great asset.
Here are some screenshots.

NDBC Bouy with data  - What Icon for NDBC Bouys?
![NDBC Bouy-Squiddio](https://user-images.githubusercontent.com/2363959/76520299-094a5000-6439-11ea-95fe-b5153e215e15.png)

ATON in Maine  - This is good too
![ATON-Squiddio](https://user-images.githubusercontent.com/2363959/76520302-09e2e680-6439-11ea-9a9c-de5e8c31e754.png)
![Squiddio-Install-Alpha](https://user-images.githubusercontent.com/2363959/76520311-0cddd700-6439-11ea-965b-77b593c7e696.png)

Preferences  - Need a check for NDBC Bouys now
![Preferences-Squiddio](https://user-images.githubusercontent.com/2363959/76520301-09e2e680-6439-11ea-8112-a864dcb8baf2.png)

Is there an easy way to have a single select for each of the data types?
Such that we hit a round button next to the checkbox and only that data is shown?
It might be very useful for the bouys.  Then if you select a checkbox, it goes back into that mode? 

Manager Plugin interface now
![Squiddio-Install-Alpha](https://user-images.githubusercontent.com/2363959/76520742-df455d80-6439-11ea-82cd-92388db0fecf.png)

This is still a work in process. Squiddio does not show its version number. Would you know why?
(It is because my Meta-URL has 0-0-0 for the date)

**PI Manager Catalog & Meta-Url**
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:pi_installer_opencpn_plugins#pi_manager_catalog_meta-url

NOTE: EDIT: Mauro, I had to revise this to be correct, I hope.

This is using the [ github.com/opencpn/plugin](https://github.com/OpenCPN/plugins/tree/Alpha)  Alpha (branch/catalog) where all the Alpha metadata xml for each plugin package is accessed via the [ocpn-plugins.xml](https://github.com/OpenCPN/plugins/blob/Alpha/ocpn-plugins.xml) file.   

Dev are allowed by bdbcat to create a very handy "META-URL".  Scroll down and see the one I submitted to the Alpha branch as a PR which Bdbcat accepted.   Well actually it is the only one in there at the moment. The format is:
```
<plugin>
<meta-url>
  <version>0.0.0</version>
  <date>2020-02-21 13:27</date>
  <plugin version="1">
    <name> Sean Depagnier Alpha Plugins meta-url </name>
    <version> 1.0 </version>
    <summary> meta-url to Sean's Alpha Plugins by rgleason </summary>
    <meta-url> https://raw.githubusercontent.com/rgleason/plugins/rg-alpha/ocpn-plugins.xml </meta-url>
  </plugin> 
```
This allows you to put the Cloudsmith metadata.xml's into your own opencpn/plugin/rg-alpha directory in my casee, run a python script to combine them all into ocpn-plugins.xml on your branch "rg-alpha", push that all up to your opencpn/plugins/rg-alpha directory.  Now you can install those plugins using the Alpha branch and the development version of Opencpn. This can be used for testing purposes.  Eventually these get moved to the Beta branch, then to the Master branch as things improve.  

I would really like to see you 
1. Fork the opencpn/plugins  repository.
2.  git checkout Alpha
3. Then add your own private branch to the fork, say  git checkout -b mc-alpha  or squiddio-alpha
4. Then git checkout Alpha again, to add your own Meta-url xml file.
4. Then to the metadata directory add your own separate xml next to mine.\

```
<plugin>
    <meta-url>
        <version>0.0.0</version>
        <date>2020-02-21 13:27</date>
        <plugin version="1">
        <name> Squiddio Alpha Plugins meta-url </name>
        <version> 1.0 </version>
        <summary> meta-url to Mauro's Alpha Plugins </summary>
        <meta-url> https://raw.githubusercontent.com/rgleason/plugins/[Your-Branch-Here]/ocpn-plugins.xml </meta-url>
</plugin> 

```
5. Then run the python script to combine the two meta-url.xmls into one  (ocpn-plugins.xml). 
6. Then push branch Alpha up to your remote repository. 
7. Then from the github web interface create a PR to github.com/opencpn/plugins  to the Alpha Branch  so that bdbcat can accept your PR and get your META-URL into the ALPHA branch.
8. The next step is to download or copy all the metadata files from your Cloudsmith Repositories that you want to have tested (all the different environments or OS)
9. Put those xml into your opencpn/plugins/[your name]-alpha branch, or squiddio-alpha branch.
10. Then check the format of each one to make sure it is right, including the urls. You need to do this at the beginning until all bugs are resolved. Make sure the tags are right.
11. Then run the python script, and then push the result up to your remote repository. 
12. Now if all is working, and bdbcat has accepted your PR,  you can install squiddio with any of the environments, using the development version of OpenCPN. 

Also see

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:pi_installer_opencpn_plugins

**Comment by mauroc** [comment]
Rick
thanks for the post. The buoy reports feature was not really meant to be used with squiddio_pi of version less than 1.2 - that's why the icons in your screenshots do not show properly (you get a little circle instead of the newly designed NDBC buoy icon). Also, the settings dialog box has changed considerably (with tabs to make it more intuitive), perhaps addressing some of your points. (I have just updated the back-end process so that the NDBC Buoy request only gets fulfilled for plugin versions >= 1.2). 
If you are up for it, you could perhaps try the new 1.2 build by downloading the package from my [cloudsmith repo](https://cloudsmith.io/~mauro-calvi/repos/squiddio-pi/packages/). (only, the Mac version is not there as the circleci build crashes due to some mac-related licensing issue I need to look into).
Thanks for the instructions on how to update the alpha channels. I am  doing some more testing on v 1.2, then want to get more familiar with the new Downloader process before I finally release it for beta.

**Comment by rgleason** [comment]
`If you are up for it, you could perhaps try the new 1.2 build by downloading the package from my cloudsmith repo. (only, the Mac version is not there as the circleci build crashes due to some mac-related licensing issue I need to look into)`

I have built your version 1.2 in my fork, and run it on a newly compiled OpenCPN master branch which is the dev version, so it was current. Windows I think.  Will try it again later.

**Comment by mauroc** [comment]
ok - let me know . BTW my build (also using the OpenCPN master branch) shows the correct plugin version. Not sure what the problem may be in your case

![image](https://user-images.githubusercontent.com/859182/76662808-61b64600-653c-11ea-822e-e711371ab6f5.png)

**Comment by rgleason** [comment]
Yes, I saw that too, but it is before you install it says 0.0.0 which perhaps makes perfect sense.

**Comment by rgleason** [comment]
I realize that perhaps you continued programming since I forked. For the version I have been working with, the Linux version works very nicely, and has better selection opportunities, for the windows version it seems to be somewhat behind.  Yours is probably better. Will try it.

**Comment by rgleason** [comment]
Mauro,  You were exactly right.  The Plugin Manager would not open and use the newer xml and I was still using the old version, due to the fact that I had used the wrong name in the  <name>Squiddio</name>  field of all the squiddio xml files.  Dave advised the name must match "CommonName" in squiddio_pi.cpp  found with a search for "GetCommonName" function.

It is some days later but I believe this is now working and I have pushed a new ocpn-plugin.xml up to my META-URL branch  rg-alpha.  So if you have a recent OpenCPN development version you can test it out in 12 different environments, by going to the Alpha Catalog and updating it, finding Squiddio and installing version 1.2 

I found that I had to close squiddio and then open again to get the icons, which had me worried for a bit. I don't know if there is a way to fix that.  I really like the tabs and the smaller real estate. I wonder if there is a way to show the full version number and date on the authentication tab?

I found that in Windows the choices for  Showing Display Text were apparently not working. That was the only problem I saw.

I think the NDBC Bouys are great and I think the formating on them is quite good and I think they'll get better in time with suggestions, programming ideas etc.   The icon is good but I wonder if you would consider a slightly different color to distinguish from anchorages?

I am just going to add some screenshots now.  Squiddio has been a good platform for me to learn and get the PI Installer Frontend Option 1 under control.  Those files are here https://github.com/rgleason/squiddio_pi/tree/ci  in the ci branch, in case you want to see how bdbcat is doing this part. I find it helpful sometimes to see how others have done it, particularly script files.

![Screenshot (618)](https://user-images.githubusercontent.com/2363959/76711766-f78ed400-66e8-11ea-9554-0437f01c05c3.png)
![Screenshot (619)](https://user-images.githubusercontent.com/2363959/76711768-fbbaf180-66e8-11ea-82c5-ff01f0c5ee7d.png)
![Screenshot (620)](https://user-images.githubusercontent.com/2363959/76711775-02496900-66e9-11ea-90d4-d4ccc9aea719.png)

I really like the change to tabs.

![Tabs-squiddio](https://user-images.githubusercontent.com/2363959/76711793-345acb00-66e9-11ea-939e-78f6af57b4d4.png)

**Comment by rgleason** [comment]
Closing this. Original problem solved.  Due to issue with ocpn-plugins.xml on rg-alpha.
This has been fixed.
