### ISSUE TITLE
Second Properties Tab issue

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#116]
1.2 Works well, nicely in fact on Windows.

Mauro, the second tab is too big I think, has settings on the bottom, put them on another tab?
![Screenshot (643)](https://user-images.githubusercontent.com/2363959/77380777-62c45000-6d52-11ea-8642-b977ea0a3d27.png)
![Screenshot (642)](https://user-images.githubusercontent.com/2363959/77380786-6657d700-6d52-11ea-8f76-bf3820707325.png)

**Comment by mauroc** [comment]
I think that's OCPN Draw's domain....I have no control over that dialog box

**Comment by mauroc** [comment]
BTW - I changed the color of the NDBC buoy icon in the latest built
