### ISSUE TITLE
Assert compiling for macOS

### ISSUE THREAD

**Issue by CarCode** [mauroc/squiddio_pi#117]
Compiling latest code for macOS I get this assert.
![AssertGridSizer](https://user-images.githubusercontent.com/666073/78460026-1835c280-76c6-11ea-92b9-a9dc1995ef48.png)

To fx it you can avoid to specify the number of rows but only the number of cols for wxFlexGridSizer. This hint can be found in the includes:
`
class WXDLLIMPEXP_CORE wxFlexGridSizer: public wxGridSizer
{
public:
    // ctors specifying the number of columns only: number of rows will be
    // deduced automatically depending on the number of sizer elements
    wxFlexGridSizer( int cols, int vgap, int hgap );
    wxFlexGridSizer( int cols, const wxSize& gap = wxSize(0, 0) );

    // ctors specifying the number of rows and columns
    wxFlexGridSizer( int rows, int cols, int vgap, int hgap );
    wxFlexGridSizer( int rows, int cols, const wxSize& gap );
`

**Comment by mauroc** [comment]
CarCode - thanks for reporting the issue. I have modified the only instance of wxFlexGridSizer that had a number of rows greater than 0 and pushed it to the repo. 
Unfortunately,  I don't have access to my Mac right now, and can't get the build to work on Circle CI. Would you be so kind to  try the latest commit from the master branch and let me know if that fixed the problem? Thank you!

**Comment by CarCode** [comment]
Mauroc
That fix it also.
The other way as I have done is to not specify the number of rows.
But then all 6 instances of wxFlexGridSizer in squiddioPrefsDialogBase.cpp have to be altered like this.

**Comment by CarCode** [comment]
I close the issue here.
