### ISSUE TITLE
Mac OS build fails on CircleCI

### ISSUE THREAD

**Issue by mauroc** [mauroc/squiddio_pi#119]
The un-install bash script fails due to some time out. No clue as to where to intervene, so opening an issue hoping for some guidance....

```
"Warning: This script will remove:
/usr/local/Caskroom/
/usr/local/Cellar/
/usr/local/bin/brew -> /usr/local/bin/brew
Are you sure you want to uninstall Homebrew? This will remove your installed packages! [y/N] 

Too long with no output (exceeded 10m0s): context deadline exceeded
"
```

![image](https://user-images.githubusercontent.com/859182/79147677-2a27fd00-7d79-11ea-94db-2ce9487bbf14.png)

**Comment by rgleason** [comment]
Mauro the PR will fix this.  The script for ci/macos-build..sh has changed because brew dropped support for the first command
