### ISSUE TITLE
Default install parameters - Uncheck show text

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#138]
Because it takes so much time upon "Enabling" the plugin to download all the POI etc
I would be best if the  Preferences "Show Text" box is unchecked so that OpenCPN does not choke on text and there is not a very long pause  while O digests and writes all this to the screen in little illegible black lines.

The other addition to this would be, when text is checked it is only written to the screen and shown at legible scales. 
That would be a huge help to improving interactivity and processing, and screen fluidity.

**Comment by rgleason** [comment]
I don't know if this might be helpful for some on RPI and slow computers, but it might.
You can close if you want.

**Comment by mauroc** [comment]
the default installation uses OCPN waypoints (not ODRAW), and it doesn't allow to select "show text" option, since text display control is not available with the current OCPN plugin APIs.  The issue can therefore be closed
