### ISSUE TITLE
Show and Hide POI  and  Show Text

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#141]
1 .When "Show Text" is unchecked  while using POI Option   oDraw textpoint,  text is not shown. However when you change to Opencpn Wpts option, the POI text is shown even when "Show Text" is unchecked.

2. Show Text check/uncheck is unresponsive in POI Option   OpenCPN waypoint.

2. Hide POI should hide any Ocpn_Draw Textpoint   AND any oDraw textpoint.
3. When the entiree world db of POI is downloaded  the Hide Local POI does not hide all the other worldwide POI.
4. There is no way to "Hide All POI"  maybe we need this seleection?

**Comment by rgleason** [comment]
We now have the API 117 for this.  
https://github.com/jongough/testplugin_pi/issues/253#issuecomment-1484134699

**Comment by mauroc** [comment]
noted! Thank you
