### ISSUE TITLE
last version update failed

### ISSUE THREAD

**Issue by mauroc** [mauroc/squiddio_pi#146]
Rick - something went wrong in the latest push.
- I merged your PR
- I updated the version number to v1.3.14.0 in the cmakelist file
- `git commit -am "v1.3.14.0 + tp1.0.176.1"` # I know I got the TP version wrong but that should not cause any issues?
- `git tag v1.3.14.0`
- `git push origin v1.3.14.0`
- `git push origin master`
- at this point I got a git error that the remote tip was ahead of the local. Tried to do a git pull with no effect, so (and this was probably my last mistake) did a 
- `git push origin master --force`

Now the [mauroc/squiddio_pi ](https://github.com/mauroc/squiddio_pi) repo is stuck on my last commit of Oct 21, my local repo is up to date with your PR and my changes (see the git log trace below) but for the life of me I can't push it to github, and get the "Everything up to date" message. 

In addition, the circle builds are all failing. 

I am kinda at a loss what to do. Any idea how to get out

`$=git log`
Author: Mauro Calvi <mauroc@yahoo.com>
Date:   Tue Nov 23 12:41:31 2021 -0800

    v1.3.14.0 + tp1.0.176.1

commit 701cf699f80a07caa1c9e3821947aa1f90853beb
Merge: d1bdc3e e261b0c
Author: Mauro Calvi <mauroc@yahoo.com>
Date:   Tue Nov 23 12:09:31 2021 -0800

    Merge pull request #144 from rgleason/master
    
    Squiddio update to TP 1.0.180  and improve Toolbar and LIsting Panel Icons

commit e261b0c4cc15a3f9103e1db3134932139d8db071
Author: Rick Gleason <fcgleason@tgp-architects.com>
Date:   Fri Nov 19 15:47:29 2021 -0500

    1.3.13.3 + TP 1.0.180 + imprv icons use svg

commit bb9cc9eb4a44dba236249b6032358426933b4dd6
Author: Rick Gleason <fcgleason@tgp-architects.com>
Date:   Fri Nov 19 15:21:09 2021 -0500

    1.3.13.2 + new svg icons

commit d1bdc3e1bd9fc3808f604724277443fd2c6f9c1e (tag: v1.3.13.0, origin/master, master)
Author: Mauro Calvi <mauroc@yahoo.com>
Date:   Tue Oct 19 16:15:36 2021 -0700

    v1.3.13.0 + tp1.0.176.1

commit 27ffdb23d1c7c94a4bcf5a3e105f874e4678379c (tag: v1.3.11.0)
Author: Mauro Calvi <mauroc@yahoo.com>
Date:   Tue Oct 19 14:56:22 2021 -0700

    updated patch #

`

**Comment by mauroc** [comment]
just thinking.....perhaps you can re-post your PR and I can repeat the process ?

**Comment by rgleason** [comment]
```
I merged your PR
I updated the version number to v1.3.14.0 in the cmakelist file
```

One thing I tend to forget is that once I merge to my remote, I then need to  git pull origin master to my local repository.
Is that perhaps what happened?

Putting the wrong TP number for the commit won't affect anything.

It looks like you figured it out.

Thanks!

**Comment by mauroc** [comment]
I did, thank you
I closed the issue as soon as I realized I had made a mistake (I am a bit rusty on git / github so I was trying to push from the wrong branch. Or was it just a senior moment? :-) )

**Comment by rgleason** [comment]
Mauro, good job.  I have done that often, after awhile you will remember.  Very nice to see you've got the process down.
