### ISSUE TITLE
SQuiddio Preferences screen on High Res screens  

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#149]
Mauro,
Perhaps I messed up preferences, but I don't think I touched anything last go around.
I am finding on this high res screen  3840x2400  that preferences looks funny and acts sub optimal.
See screenshot below please. Do you think you could fix that
![Screenshot (152)](https://user-images.githubusercontent.com/2363959/146802016-945d42a4-23a2-4b23-9db1-8429e234f784.png)
?

**Comment by mauroc** [comment]
Rick - I never noticed this, perhaps because I don't have a screen with that resolution (I assume this is Windows?).
Did you just click on the squiddio icon  in the sidebar and got that?
I can take a look.
Thanks for flagging the issue

**Comment by rgleason** [comment]
Yes, I just clicked on it. 
Ive found several other plugins with similar issues due to the high res

**Comment by mauroc** [comment]
seems like a wxwidget issue perhaps? Closing the issue as not squidddio-specific.

**Comment by rgleason** [comment]
Ok, I think I am going to try to fix it. Thanks.
