### ISSUE TITLE
New Feature: Ability to add POI when offline.

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#19]
I would like to be able to add POI when offline, extemporaneously. Then be able to upload them when connected to the internet. It would probably increase the number and quality of POI. There might be some additional things to do with each POI when uploading the POI. I think this could be handled in some way.

**Comment by rgleason** [comment]
This is old, but might be useful for cruisers, as the notes will most likely be more accurate this way, but Mauro, you can close this if you want to.

**Comment by mauroc** [comment]
this is actually a feature request (and a good one, but a lot of work) in Flyspray. Not really an Issue proper
