### ISSUE TITLE
New Feature: Shift POI to a layer or SQnavobj.xml?

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#20]
Also it would be great if the POI were shifted to a layer similar to what the OcpnDraw does, using ODnavobj.xml file. I guess squiddio could use a SQnavobj.xml file? Jon Gough's excellent plugin would have a lot of the necessary code and he might lend a hand too. --Perhaps it could use the OcpnDraw ODnavobj.xml? but then would that plugin have to be installed and active? Maybe not. These are questiions...

**Comment by rgleason** [comment]
https://opencpn.org/flyspray/index.php?do=details&task_id=2348

**Comment by rgleason** [comment]
In https://github.com/jongough/ocpn_draw_pi/issues/386#issuecomment-385106524

Jon Gough wrote:

> OD is a drawing tool for OCPN, it is not intended to be anything else. For importing the anchorages you 'could' convert a real gpx file into an OD 'gpx like' file, i.e. from gpx <wpt ...> to <opencpn:ODPoint ...> . You 'could' convert an to opencpn:pathopencpn:typeBoundary</opencpn:type>, but you have to remember that boundaries have the start point and end point being the same ODPoint so that the boundary can be 'closed' which a route is not.
> 
> I have added in OD 1.5 a new API for creating boundaries, boundary points and text points. The text point API was built to help with the 'squiddio' plugin and the use of text points rather than opencpn waypoints for points of interest. After all text points were designed to have extra information displayable about points of interest. However, as yet, the squiddio developer has not shown interest in this capability preferring to keep using opencpn waypoints.
> 
> As OD 1.5 is currently a work in progress extra import/export capabilities can be added, but it may take a little while.

**Comment by rgleason** [comment]
I think Jon has done this. Should this be closed now?

**Comment by mauroc** [comment]
Rick
sorry for the delay in responding. I have been on a long passage for the
last couple of weeks.
Yes, this has been done by Jon and the case can be closed
Best
Mauro

**Comment by rgleason** [comment]
Thanks, Mauro!  Hope you've enjoyed some good weather.  Also Thank you Jon1
