### ISSUE TITLE
New Feature: Toggle Show/Hide of the Log

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#21]
The other item would be adding an ability to toggle show/hide of the Log when sending and recieving Logs from friends.

**Comment by rgleason** [comment]
https://opencpn.org/flyspray/index.php?do=details&task_id=2350

**Comment by rgleason** [comment]
Old, also not so sure if this is critical. Mauro, you can delete if you want.

**Comment by mauroc** [comment]
good request, but not  a huge priority due to limited adoption of the log feature....
