### ISSUE TITLE
Unknown image data format

### ISSUE THREAD

**Issue by arivarton** [mauroc/squiddio_pi#25]
After running:
git clone git://github.com/mauroc/squiddio_pi
cd squiddio_pi
cmake -DCMAKE_INSTALL_PREFIX=/usr/ CMakeLists.txt
make
sudo make install

This happens when i go into plugins in opencpn:
22:58:33 GMT: PlugInManager: Loading PlugIn: /usr/lib/opencpn/libsquiddio_pi.so
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT: Warning: Unknown image data format.
22:58:33 GMT:   /usr/lib/opencpn/libsquiddio_pi.so
              API Version detected: 113
              PlugIn Version detected: 7
... 
22:58:39 GMT: PlugInManager: Initializing PlugIn: /usr/lib/opencpn/libsquiddio_pi.so
22:58:39 GMT: squiddio_pi: Init()
22:58:39 GMT: squiddio_pi: getting .gpx layer files from: /home/vidr/.opencpn/squiddio

[gist](https://gist.github.com/arivarton/a9c0374c80c2f4db4256a66427f0ee7e)

And then opencpn freezes.

This is on Arch Linux.

**Comment by rgleason** [comment]
This is pretty old and the plugin has moved on. Shouldn't it be closed? Mauro you would be the only one who can close it other than the OP.

**Comment by rgleason** [comment]
Mauro, the OP has not responded, this is for Arch Linux, and is last year.
I think it should be closed, we have gone past that problem.
You and OP are the only ones who can close it.

**Comment by mauroc** [comment]
Issue is from developer who has moved on and will not respond to messages. Also , about Arch Linux so not extremely critical
