### ISSUE TITLE
Change to OD_textpoints - Icons don't show until restart Opencpn.

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#36]
When you change from waypoint to OD_textpoints, you must shutdown Opencpn and restart to have the squiddio icons show properly.

**Comment by rgleason** [comment]
Is this fixed now?

**Comment by mauroc** [comment]
I can't reproduce the problem on Debian or Mac OS. Looks like it has been fixed

**Comment by rgleason** [comment]
This happens in Windows.  I just repeated it again.
1. Disable Squiddio.
2. Enable Squiddio. 
3. Click on the Icon.
4. The Icon goes black.
5. The only way to fix it is to shutdown Opencpn and restart it.
6. Then the Icon shows again.

![Screenshot (135)](https://user-images.githubusercontent.com/2363959/66091996-1abd3100-e558-11e9-9ae6-b79889aa43e7.png)
![Screenshot (136)](https://user-images.githubusercontent.com/2363959/66091998-1d1f8b00-e558-11e9-9854-a7d590ed948f.png)
