### ISSUE TITLE
Update  .travis.yml   for 'tag push to git release'

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#40]
Mauro,
Please see
https://github.com/rgleason/squiddio_pi/blob/od_fixes/.travis.yml

for a more current version of .travis.yml that will give you the 7 assets.
I will try to make a PR later, if you don't get to this.

also  it looks like your appveyor file
https://github.com/mauroc/squiddio_pi/blob/master/appveyor.yml
is very similar to 
https://github.com/rgleason/squiddio_pi/blob/od_fixes/appveyor.yml

with the exception of 
your Line 59 #  tag: v1.0.6 # insert version name
instead of
my line 59   tag: $(APPVEYOR_REPO_TAG_NAME) # insert version name

How do you use this?   Uncomment when you want to push a tag and enter the correct version?  
or is it unneccessary?

Once this is done, you could add a new tag v1.0.11 and push the tag to your remote repository which should push a new release v1.0.11 to create the files under the release tag. 

Then we could advise Kathi to change the source for the downloads page from this mine https://github.com/rgleason/squiddio_pi/releases to yours!   Then your repository will be providing the releases!  That will be a good improvement.

**Comment by mauroc** [comment]
> I will try to make a PR later, if you don't get to this.

let me give it a shot

I took my appveyor and .travis yml files from your squiddio_pi repo, hence the similarity. 
I found that not having line 59 causes appveyor to release the build under the current tag, just like .travis.yml , so I felt it was unnecessary.   But again, I am kind of fumbling in the dark here so let me know if  you see it differently.

( BTW Where is the APPVEYOR_REPO_TAG_NAME constant supposed be set? )

> Once this is done, you could add a new tag v1.0.11 and push the tag

Wait..what happens to PR #39? Leamas advised me not to merge it so I am on standby...
Also my current master is at v1.0.5..how did we get to v1.0.11?

**Comment by leamas** [comment]
@mauro: this is really between you and Rick. That said, as an upstream maintainer I would never accept a PR which updated release versions. This is your task and no one's else.

**Comment by rgleason** [comment]
Leamas, you have a more rigid approach than we have been working under. As I have said before, if I did not create windows exe installers, almost from day one of this plugin, we would not have had the squiddio pi for Windows.  When there has been a change, I have incremented the patch version.

I have provided[ this link a](https://github.com/rgleason/squiddio_pi/releases) number of times to you two gentlemen, but neither of you seem to understand.  I have regarded myself as a "whatever you want to call it" of the windows version of this plugin for sometime.   Mauro has not had travis or appveyor accounts until now, therefore since v1.0.5 the Windows plugins have been updated accordingly.  Since Mauro is in the process of setting this system up, it is appropriate that his travis and appveyor be modified to support the current system, as bdbcat has said.

If you want to keep the version patch at 5, I think it is a very bad idea since we have released v1.0.10, because many will be confused by going retrograde.

**Comment by rgleason** [comment]
PS I will continue to support Windows version of this plugin using the current process, until Mauro has worked out travis and appveyor and can do so on his repository.

**Comment by rgleason** [comment]
> I found that not having line 59 causes appveyor to release the build under the current tag, just like .travis.yml , so I felt it was unnecessary. But again, I am kind of fumbling in the dark here so let me know if you see it differently.
> 
> ( BTW Where is the APPVEYOR_REPO_TAG_NAME constant supposed be set? )

I have been using this line and it works, but perhaps it is unnecessary.  The line was in an example that I reviewed sometime ago.  I would have to go back and follow the old process to find out where it came from.

These are parts of the documentation that cover APPVEYOR_REPO_TAG_NAME
https://www.appveyor.com/docs/branches/
https://www.appveyor.com/docs/deployment/
However they do not cover the TAG: ... line.

**Comment by leamas** [comment]
> If you want to keep the version patch at 5, I think it is a very bad idea since we 
> have released v1.0.10, because many will be confused by going retrograde.

Well... I cannot see much else that that you have caused this confusion, and I think you just have to announce the bad news to your users.

Your repository is downstream from this one owned by @mauroc. In this situation you never, ever change the upstream version, full stop.  The version scheme you could use here is for example a release tag like 1.0.5-1, 1.0.5-2 etc.

Full-blown versioning system, like those used by linux distros, have an epoch: prefix which can be used to resolve situations like this. However, introducing an epoch here is IMHO overkill, and also violates the semantic version syntax.

As I see it you have two options: Rewrite the PR, dropping the changes in version completely. Or announce that your repo is a fork. This means basically that you intend to maintain it independent of mauroc's repo.  While forking is OK, it is usually accompanied by changing name so that users can distinguish your repo from mauroc's

I don't think forking is justified given the circumstances.

**Comment by rgleason** [comment]
Mauroc can just change the version to 1.0.11.

I have done this with most of Sean's plugins to, sometimes for years. This is a totally new requirement nobody has advised about.

Is this something required because of linux versioning, flatpak or something?

**Comment by rgleason** [comment]
Before when we had version.major.minor I would add an "a", "b" "c".  So now that patch has been added, what the xxxx is it for? 

This rule makes no sense to me. Totally arbitrary.

**Comment by leamas** [comment]
> does not compile so changes must be made to the windows version, or there is some fixable problem

What you should do in such cases is to submit a PR which eventually is merged upstream. Small, bug-fix type PR:s are usually accepted without much fuzz.  This is exactly how we work with for example the opencpn project. Some of us submit's PR, some smaller, some larger. But we *don't*  release our own versions with simple bugfixes for reasons I'm sure you can follow.

When the PR is accepted you are in a much better position to make a downstream release if required.  Linux package maintainers do such things. We basically patch upstream as required for platforms like Debian or Fedora, sets a new release number (not version!), releases the package and submits the patches upstream as PRs. Seems like you are doing similar things for win32 (?) 

Personally, I think the best would be if you could split your PR into multiple, smaller ones. That would make it much easier to review and merge. But, this is not my call, it's @mauroc's (and your's!)

**Comment by leamas** [comment]
> Is this something required because of linux versioning, flatpak or something?

It is just how it works: .deb,  .rpm, npm, pypi,  rubygem, .pkg, choco, homebrew, perl, flatpak... just any sane  version system. You are probably not in a position to invent something new here ;)  

I can understand if you are somewhat confused, it can be your windows background. Windows is probably the only larger platform without a native component version system.

**Comment by leamas** [comment]
> Mauroc can just change the version to 1.0.11

Perhaps. Or 1.0.12, 1.0 6  or whatever -- after all, he is the upstream maintainer.  You could of course ask him to do it to save your users from your mistake. This would not have been a problem if you had used a sane version like 1.0.5-2 or so.

Submitting a PR with a new version is IMHO asking for trouble.

**Comment by rgleason** [comment]
Leamas,
Not Windows, really. I come from the past. I had fortran on an IBM360 (?) in college, computer science 201 and 301, with punch cards (1971!  Later learned Pascal to program our CAD system and made a number of extensions and macros (1985-1995). Then started with Opencpn about 7-8 years ago.

Leamas, in order to push a tag to a release you need to change the version. I have often needed to do that to get a windows version.

So you would like me to use  1.0.11-2  but I believe that no longer works with the programming in place.  We have quite recently changed to major.minor.patch and I thought the patch was for situations I would be presented with.

**Comment by leamas** [comment]
> Leamas, in order to push a tag to a release you need to change the version.

The hairy details: The complete  designation is name-version-release a. k. a. nvr. When I package a version like 1.2.3 I tag it with for example 1.2.3-2. So yes, you need a unique number for your release, but you tack it on the existing version without changing it. This way, the next upstream version  supersedes your release as it should.

> So you would like me to use 1.0.11-2 but I believe that no longer works with the programming in place

Then you either need to change the programming, or find another scheme which fits the bill. The semantic version scheme is basically something like 1.2.3-alfa, where alfa is the pre-release tag. You should be able to use that part, your releases are pre-releases of upcoming ones.

> What happens when I submit a PR and nothing happens or there is not a new version for windows that is built? We just wait and wait for it to happen. I won't work that way.

Of course not. You build your package, possibly with  a new release number and submits the patches required upstream.

**Comment by rgleason** [comment]
Well I am perfectly willing to change to a new system/process, but there are still unknowns here, the rules are not clear, and I also have to get my head around this, bear with me.

Maybe we need some notes somewhere about this?

**Comment by rgleason** [comment]
I had asked that the plugins show the semantic versioning   xxx.xxx.xx in their preferences window to aid users, maintainers, programmers etc.   thinking that the patch part would be used by guys like me. 

You have now for other reasons have  changed that advantage and asked that I use some other addon designation that will not be seen.   - This could go on and on. I could then ask to see be able to see that addon designation so windows users would know what version they are using. Where does it stop?

**Comment by leamas** [comment]
> the rules are not clear, and I also have to get my head around this, bear with me.

The rule is simple: when you patch an upstream version (mauroc's squiddio here) you don't touch it's version. If you release something, add our own number to this without changing it. This way things *just works* (tm) when upstream version numbers are updated

>  think the coding for semantic versioning xxx.xxx.xx no longer allows xxx.xx.x-alpha but I could certainly be wrong.

Indeed. It actually allows for a dot-separated series of labels, with sorting criterias.

> Maybe we need some notes somewhere about this?

I don't think so. This is just how things are done....

> I had asked that the plugins show the semantic versioning xxx.xxx.xx in their preferences window to aid users, maintainers, programmers etc. thinking that the patch part would be used by guys like me.

Which is to say that it should *not* be used by upstreams... and IMHO this won't work. Have you found any examples where such a scheme is used? Reading the semver.org specs, can you find any support for using the patch number this way?

> You have now for other reasons have changed that advantage and asked that I use some other addon

I just ask you to use existing best practices for these things. And avoid something which as I see it just won't work. One example is that using 1.0.11 for the upstream is plain wrong since it's very different from your downstream 1.0.11.

Yes, it requires some changes in interfaces. Alas, such things happens from time to time :(

**Comment by rgleason** [comment]
https://semver.org/

> 6. Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

> 7. A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

**Comment by leamas** [comment]
>  I think I am going to need to use no. 6 and be upstream.

Well, in that case you should certainly talk to @mauroc who is the upstream maintainer. The basic flow is that you send the bugfixes as PR:s, @mauroc merges them and then releases a new version.  

Note that the changes introduced when merging #35 perhaps are big enough to require a new minor version like 1.1.0.

**Comment by rgleason** [comment]
So simply to explain, for Sean's Plugins, how would I make a release version without changing the version?

This is counter intuitive.

**Comment by leamas** [comment]
As a downstream packager you don't change the release. Instead, you make whatever patches needed and uses a release number based on upstream's, tacking some own release to the original version. So, if the original version is 1.2.3 you could use for example 1.2.3-1 or even 1.2.3.1. 

This is actually intuitive. version-release like 1.2.4-6 should be read "Upstream's version 1.2.4 + local patchset 6" which is what it is.

In parallel process you upstream the patches as PR:s to upstream. If you cannot do this you will have to rebase them for each new upstream release. You don't want that....

**Comment by rgleason** [comment]
OK, Got it.
"As a downstream packager you don't change the release. Instead, you make whatever patches needed and uses a release number based on upstream's,"
 The correct process is:
1. "If the original version is 1.2.3, use for example 1.2.3-1 or even 1.2.3.1."
2. Then "upstream the patches as PR:s to upstream. If you cannot do this you will have to rebase them for each new upstream release (which you don't want to have to do).

I think this needs to be written up in the Dev Wiki along with the Versioning scheme and will try to start such a page.

**Comment by rgleason** [comment]
Alec,  what will show as the version using the API?
1.2.3 ?  or
1.2.3-1 ?   1.2.3.1. ?

**Comment by leamas** [comment]
Since we are using semantic versioning we use the pre-release field i. e., 1.2.3-1. It's not ideal, but probably the best we can do given the limitations

**Comment by leamas** [comment]
> As a downstream packager you don't change the release.

It's a little more clear if you stick to the common convention that upstreams defines the version and downstreams  the release.

**Comment by rgleason** [comment]
Will stick to convention then using
1.2.3-1
1.2.3-2
1.2.3-3
and making PR to upstream.
Will this 1.2.3-3 show in the version field when the plugin uses the api tools?

**Comment by leamas** [comment]
My PR works with and shows the semantic version, basically 1.2.3-tag+buildinfo. In the end, it's about what the plugins returns.  Which, if you want more than 1.2 requires merging my PR or something similar.

**Comment by rgleason** [comment]
Great.

**Comment by leamas** [comment]
Dammit. It's actually not that great. 

(Mis)using the pre-release tag as downstream release is actually a bad idea since it will sort before the upstream release.  While the semver.org specs doesn't really support any specific post-release scheme we are free to interpret the specs.

I'll add support in OpenCPN/opencpn#1460 for a fourth version number for a total version like MAJOR.MINOR.PATCH.RELEASE where release is an optional post-release number.

Which basically boils down to downstream releases like 1.2.3.1, 1.2.3.2 etc. for upstream version 1.2.3. This should be simple enough, leaving the pre-release tag to what it's intended for and sorts ok.

**Comment by rgleason** [comment]
Yes,  this seems fine to me.  A Big Thankyou from me!
Will the cmake files need some adjustments for this or not?

**Comment by leamas** [comment]
As a starter, nothing will happen until the PR is merged.

When merged, the change you will have to do is to update the plugin's   GetPlugInVersionPost() method.

As for the cmake files, you might want to give the files a name including the post release number.  Today here is no support for that. You should be able to fix this even if the PR isn't merged.

**Comment by rgleason** [comment]
Alec, I have saved this link, for future use in a Wiki page discussing semantic versioning in O.
Closing.

**Comment by rgleason** [comment]
Alec is the PR that needs to be merged, this one for Opencpn?
[Version: Extend plugin version info API + display extended version info #1460](https://github.com/OpenCPN/OpenCPN/pull/1460)

**Comment by rgleason** [comment]
https://github.com/OpenCPN/OpenCPN/pull/1460/commits/9fc16c8eedb3b811ba93c85f18dd40e8b6359e35
Notes 
 * Versions uses a modified semantic versioning scheme:
 * major.minor.revision.post-tag+build.
 * for example 1.2.6.1-alfa+deadbee. The values major, minor, revision
 * and post should be integers. The tag is a pre-release marker, the build
 * part is build info.
 
Parsing and comparing follows the spec besides
 *   -  the pre-release tag which is sorted strictly lexically
 *      (no dotted parts or numeric ordering support).
 *
 *   -  The post part which is post-release number, typically used in
 *      downstream releases.
 * See: https://semver.org/

** /include/ocpn_plugin.h**  

GetPlugInVersionMajor()
GetPlugInVersionMinor()

virtual int GetPlugInVersionPatch();
virtual int GetPlugInVersionPost();
virtual const char* GetPlugInVersionPre();

`From src/pluginmanager.cpp`
```
   return SemanticVersion(plugin_117->GetPlugInVersionMajor(),
                               plugin_117->GetPlugInVersionMinor(),
                               plugin_117->GetPlugInVersionPatch(),
                               plugin_117->GetPlugInVersionPost(),
                               plugin_117->GetPlugInVersionPre(),
                               plugin_117->GetPlugInVersionBuild());
```

Each Plugin will need modify code using these tools to show the full Version number in the Preferences and the Option > Toolbar list.

@leamas 
Is this note correct?
* major.minor.revision.post-tag+build.   **<---Does not match the code really, will lead to confusion**
 * for example 1.2.6.1-alfa+deadbee. The values major, minor, revision
 * and post should be integers. The tag is a pre-release marker, the build
 * part is build info.

**Comment by rgleason** [comment]
Learned how to make the above note in the code.

**Comment by rgleason** [comment]
For example:

In squiddio_pi.cpp after similar GetPluginVersionMinor  line around Line 925 add

```
if  PluginAPI=117 then
int squiddio_pi::GetPlugInVersionPatch() {
    return PLUGIN_VERSION_PATCH;
int squiddio_pi::GetPlugInVersionPost() {
    return PLUGIN_VERSION_POST;
const squiddio_pi::GetPlugInVersionPre() {
    return PLUGIN_VERSION_PRE;
const squiddio_pi::GetPlugInVersionBuild() {
    return PLUGIN_VERSION_PRE;


```In squiddio_pi.h  after similar GetPluginVersionMinor line add
under  //    The required PlugIn Methods
```
if PluginAPI=117 then
int GetPlugInVersionPatch();
int GetPlugInVersionPost();
const GetPlugInVersionPre();
const GetPlugInVersionBuild();

```

in \cmake\version.h.in  add
```
if PluginAPI=117 then
#define PLUGIN_VERSION_POST ${VERSION_POST}
#define PLUGIN_VERSION_PRE ${VERSION_PRE}
#define PLUGIN_VERSION_BUILD ${VERSION_BUILD}
```

in CMakeLists.txt add after  SET(VERSION_PATCH "xx")
```
if PluginAPI=117 then
SET(VERSION_ POST "")
SET(VERSION_PRE "")
SET(VERSION_BUILD "")
```

Similar changes will be needed in PluginPackage.cmake at the beginning.

Then changes need to be made to the 
Options > Plugins  window to show the full version number
Preferences Window to show the full version number.

Jon Gough had this all worked out in od_fixes but it did not make it with the rebase.
