### ISSUE TITLE
Now other ramps don't show.

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#42]
http://www.cruisersforum.com/forums/f134/squiddio-plugin-132122.html#post2992259

Possibly as a result of this 
https://github.com/mauroc/squiddio_pi/issues/37

**Comment by mauroc** [comment]
there was a missing statement in the code. Fixed with v1.0.11

**Comment by rgleason** [comment]
Thanks Mauro. Will test it tomorrow.

**Comment by mauroc** [comment]
fixed in v1.0.11

**Comment by rgleason** [comment]
Mauro  it works fine with both ramp icons now. Thankyou.
Wondering about the squiddio icon that goes blank (black) after opening the preferences window several times. Just discovered that when I use the bars at the top of the toolbar to hide the menu and then unhide the squiddio icon is showing again.  It's a minor bug, perhaps related to the order of rewrite of the icon or something?
