### ISSUE TITLE
#35: everything broken.

### ISSUE THREAD

**Issue by leamas** [mauroc/squiddio_pi#48]
When #35 was merged all circleci builder worked (although the deployment wasn't completely configured). Current master does not build any of the plugin loader artifacts, several files are removed or completely reset to another version without any visible attempt to merge the changes done.

I don't really understand the situation. Are these changes on purpose with the goal to get rid of any changes aiming to provide the artifacts required by the plugin installer? Or is it just some mistakes?

"Mystified"

**Comment by rgleason** [comment]
Leamas, I believe I speak for Jon and Mauro too, I am certain it is unintentional, we are very much in support of the Plugin Installer and trying have Plugin Installer work alongside the current git deployment to release tab system.

What do you think broke it?

**Comment by rgleason** [comment]
mingw 
```
#!/bin/bash -eo pipefail
ci/circleci-build-mingw.sh
+ set -xe
+ su -c 'dnf install -q -y sudo dnf-plugins-core'
+ sudo dnf -q builddep -y mingw/fedora/opencpn-deps.spec
Failed to open: 'mingw/fedora/opencpn-deps.spec', not a valid spec file: can't parse specfile
Error: Some packages could not be found.   Exited with code 1
```

flatpak
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  **Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)**
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindwxWidgets.cmake:990 (find_package_handle_standard_args)
  cmake/PluginConfigure.cmake:78 (FIND_PACKAGE)
  CMakeLists.txt:42 (INCLUDE)
-- Configuring incomplete, errors occurred!
```

**Comment by rgleason** [comment]
Alec, 
On mauroc/squiddio_pi "test_dep" branch, where I can see your merged PR's #35 & #38, I do not see any ci/builds at any stage.  

Perhaps this will take a bit more work? Figuring out why?

**Comment by mauroc** [comment]
the test_dep branch was just me messing around with the code,
unsuccessfully. It should be ignored

**Comment by rgleason** [comment]
I think we need to do the following:
1. Get the merge of od_fixes and Plugin Manager accomplished somehow. We need a strategy, using which branch, and what to do exactly.
2. Then make any additional necessary changes for fixes and od_fixes and plugin_manager, but one at a time, like trains on a single track with a token!
