### ISSUE TITLE
ci: travis: The builds are duplicated.

### ISSUE THREAD

**Issue by leamas** [mauroc/squiddio_pi#54]
Each commit is built twice by Travis. Seems to be some kind of weird configuration issue.

**Comment by mauroc** [comment]
hmmm...weird. I have not seen that happen to me

**Comment by leamas** [comment]
You can see it in master right now. In the code view with the commits there is a green check mark on the top commit [f7d1bb8]. Right-click on this and you can see the first entry *Travis CI - Branch — Build Passed* and the last *continuous-integration/travis-ci/push — The Travis CI b...*.

**Comment by mauroc** [comment]
got it. Have no idea why that happens

**Comment by leamas** [comment]
Nor have I. A first check could perhaps be to log in to travis-ci.org and check the Settings there.  At a glance I see a *Build pushed branches* checkbox, by default on. Perhaps one of the builds disappear if you uncheck this?! Or is there a setting for the other build?

"Confused"

**Comment by rgleason** [comment]
Perhaps this will explain the problem and provide some avenues for "contributors" without getting too complicated.
https://stackoverflow.com/questions/23380369/defining-secure-environment-variables-for-multiple-repositories-in-a-single-tra

**Comment by leamas** [comment]
Perhaps. Note how the cloudsmith deployment walks around this mess without any need for encryption (while still playing it safe).

**Comment by leamas** [comment]
@rgleason: BTW: Could you please stick to the subject? This issue is about duplicated builds, nothing else. I will delete the answer I wrote before reading the header...

**Comment by rgleason** [comment]
https://docs.travis-ci.com/user/pull-requests#double-builds-on-pull-requests

**Comment by leamas** [comment]
https://stackoverflow.com/questions/34974925/travis-ci-creates-two-builds-for-each-github-commit-push/34975730

The answer is a little old, but seems to still be valid.

**Comment by leamas** [comment]
Now, after merging #99 we don't use the travis builders anymore. That's the ultimate fix.
