### ISSUE TITLE
travis osx build doesn't deploy anything to Github releases

### ISSUE THREAD

**Issue by mauroc** [mauroc/squiddio_pi#55]
the build completes successfully, but the only artifact it generates is squiddio_pi-{.....}.**tar.gz**
However, the .travis.yml file in the deploy section doesn't have .tar.gz as a file extension, so it doesn't deploy the package. I added the extension to the list and it seems to work. 

Is that the intended result?

**Comment by leamas** [comment]
No, it's supposed to build the .dmg installation image.

I'll take a look later
