### ISSUE TITLE
free opensource MacOs builder plan on circleci: limit to 500 minutes/month

### ISSUE THREAD

**Issue by mauroc** [mauroc/squiddio_pi#59]
one more reason to trigger builds only upon new versions submissions (e.g. git push origin v1.0.14) like in travis. 

500 minutes/month is not a lot if you consider that these are time consuming build processes. ....

I don't know if I just got the "johnny come lately" plan or it's the same limitation for everyone.
Just a thought. Not particularly urgent

**Comment by rgleason** [comment]
I was told by circleci support to remove the config.yml lines related to macos build because that requires a different plan, and she thought these lines were causing the particular errors I had, however I see the MacOs build worked.

**Comment by rgleason** [comment]
Found this page  Build on macOS 
https://circleci.com/open-source/
...If you’re building on macOS, CircleCI offers 25,000 credits per month ($180 annual value) free to open source builds. To get access, contact us at billing@circleci.com.

**Comment by leamas** [comment]
The macos builds tend to take around 5 minutes. That makes 100 builds, or three per day. It might not be a problem in the long run. 

> one more reason to trigger builds only upon new versions submission

Indeed. Would be a simple fix.  But a pain if there are bugs from the past popping up.

I suggest the dreaded wait and see approach... If we run out of macos build time at the end of the month it shouldn't really be that big a problem

**Comment by rgleason** [comment]
Based on mauro's current master, before Jon's commit, this branch had appveyor and travis complete, circleci had an error due to macos not enabled. Circleci is going to enable it I believe.
https://github.com/rgleason/squiddio_pi/commits/reset35-rg

**Comment by rgleason** [comment]
Perhaps it would be useful to be able to turn on and off the circleci deployment?  Similar to pushing a tag to github to push new version files to the release tab?  ..initiate it when you think it is ready, or maybe even a trial test first to be able to correct things,  before the actual file deployment?  Or is that too complicated?

**Comment by rgleason** [comment]
Skipping or Canceling a Build 
https://circleci.com/docs/2.0/skip-build/#section=jobs
"adding a [ci skip] or [skip ci] tag anywhere in a commit’s title or description. This not only skips the marked commit, but also all other commits in the push."

**Comment by mauroc** [comment]
> "adding a [ci skip] or [skip ci] tag anywhere in a commit’s title or description. This not only skips the marked commit, but also all other commits in the push."

this is really helpful and may take care of the 500 minute cap on Macos for the time being. Based on this, and alec's suggestion for the wait and see approach, I am going to close the issue
