### ISSUE TITLE
Our old friend Ventura Boatyard not showing

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#62]
Using version 1.0.17  although there is no way to determine that from Preferences "1.0"
it appears that the green boat ramp is missing again perhaps?

![Screenshot (175)](https://user-images.githubusercontent.com/2363959/67128188-eccb2400-f1c8-11e9-8ca9-418135ba9f2b.png)

Similar problem to 
https://github.com/mauroc/squiddio_pi/issues/37

**Comment by mauroc** [comment]
yep - looks like that fix got lost in the recent rebasing. I'll put it back in
