### ISSUE TITLE
Full Version visible upon next Plugin API release?

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#68]
Is it possible to do this

If plugin api =>API 1.17 then 
    Show full version number in preferences and in Options > Plugins  display
    (Major.minor,patch etc) Just as a single line 
else

**Comment by leamas** [comment]
No. 1.17 only exists as a PR.  Nobody knows if/when this is merged, or how it looks after possible review and/or rebasing.

Of course, it's possible to make a `#if` handling this, basically removing the stuff until API reaches this version. Given the uncertainty involved I'd advice against it. 

OTOH, some comments in the right place certainly makes sense.

**Comment by rgleason** [comment]
> Of course, it's possible to make a #if handling this, basically removing the stuff until API reaches this version. Given the uncertainty involved I'd advice against it.

Understood,  It is inevitable there will be a plugin api 1.17 but exactly what it looks like is unknown. You're the pro.

> OTOH, some comments in the right place certainly makes sense.

Trust you or Jon will do that in one of the cmake files so that Plugin Authors understand what is necessary to extend the version number display using the api.

Should I close this?
