### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [mauroc/squiddio_pi#7]
Hi!

It would be very usefull to have tagged releases, so the source for a specific version of th eplugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier. 

I'd like to package this plugin for Gentoo Linux and for that it requires a reliable specific download URL for the releases. 

Thanks in advance!

**Comment by mschiff** [comment]
ping?

**Comment by mauroc** [comment]
@mschiff : sorry it took so long. I have created release 0.7. Let me know if that works for you and good luck with the Gentoo version

**Comment by mschiff** [comment]
Thank you very much. Works good!
