### ISSUE TITLE
PKG name convention  -fix version to X.X.X.x for github release

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#70]
Now outputs:
Squiddio-Plugin_1.0.17-ov50-1.16.pkg
https://github.com/rgleason/squiddio_pi/releases/tag/v1.0.17-test3

Others are 1.0.17.1

**Comment by leamas** [comment]
Indeed. The last part is the release identifier aimed to make it possible to make downstream releases. This is not taken care of by the semantic versioning scheme. In particular, semantic versioning uses the hyphen as a 'post-release' delimiter and thus collides with the traditional version-release scheme used in linux distros.

I have added support for this last identifier into https://github.com/OpenCPN/OpenCPN/pull/1460

**Comment by rgleason** [comment]
Yes, but forgive me Alec, if I don't get it. Why doesn't the macOS file show

Squiddio-Plugin_1.0.17**.1**-ov50-1.16.pkg 

Like the other file names, for consistency?

**Comment by leamas** [comment]
No idea, you have to look into the cmake code. Perhaps @jongough  has some input?

**Comment by jongough** [comment]
The naming of plugins is inconsistent across platforms. For linux you need to have "opencpn-plugin" as the first part or it does not show up in the installation software. Care also needs to be taken with the version numbering or again the changes/updates will not show in the installation/update process.

I tried to make the changes consistent with what is already done for windows, macos and linux for the first part of the name up to and including the version numbering of the plugin. I have added 'tweak' as a further level of versioning as that is the name provided in cmake.

The last part of the versioning specifies the level of OpenCPN which is a minimum for use and the OCPN API version number which it will work with. I am not wedded to the naming, but was trying for something that would give useful information before installing the plugin then wondering why it did not show up in the list of available plugins.

I think there needs to be agreement on the naming of plugins and OCPN across platforms. This may need to be a decision made by Dave (or others) who have the 'bigger' picture.

I can (or anyone can) change the naming quite easily in cmake if what has been done is not acceptable.

**Comment by rgleason** [comment]
Jon, I am sure you've considered this much more carefully than I have. Thank you.

**Comment by rgleason** [comment]
When everyone is just using the new Plugin Manager the naming will become more consistent.

**Comment by rgleason** [comment]
https://github.com/mauroc/squiddio_pi/pull/76

**Comment by rgleason** [comment]
It is a discussion, and not really an issue. Will see how to name the github release   .exe as "ov50"
Closing.

**Comment by rgleason** [comment]
It looks to me like files are being renamed again for upload to cloudsmith.
Is part of why the  windows .exe files get renamed without  "ov50"?
Some of this is getting confusing again.  Why have version.sh.in? What does it do?

 **pkg_version.sh.in
@@ -0,0 +1,4 @@
VERSION=${PACKAGE_VERSION}.${PKG_RELEASE}
VERSION_DATE="${GIT_COMMIT_DATE}"
PKG_TARGET=${PKG_TARGET}
PKG_TARGET_VERSION=${PKG_TARGET_VERSION}**
