### ISSUE TITLE
Eclipse Debug broken

### ISSUE THREAD

**Issue by mauroc** [mauroc/squiddio_pi#78]
for years I have been using Eclipse IDE (Version: 2019-03 (4.11.0)) running on Ubuntu (v 18.04) to debug squiddio_pi. 

I noticed the other day that Debug was skipping all breakpoints I add in the squiddio_pi code (while it executed correctly the ones in the opencpn code). 

I restored a commit I made on 10/17 (b82d6d9ba4c0f59cd19a9389cfb590b7f93d41ae) and that one worked correctly. 

I traced down a the potential offending commit to this one on 10/17:
https://github.com/mauroc/squiddio_pi/commit/e7876fc0f74b3ad225e1d04c69d28f5a748c5ebe 

particularly this change made to CmakeFileslist.txt

![image](https://user-images.githubusercontent.com/859182/67319163-6ad94480-f4c1-11e9-960d-35751844427c.png)

Apparently, eclipse (or gdb, which I understan eclipse uses as debugger) uses that information to derive the location of the squiddio_pi project name, and therefore code. 

Does this make sense to anyone? Anyone had a similar problem? I suppose there must be other coders out there using eclipse? Can that line just be restored?

I am not a huge C++ guy (my background is mostly Ruby backend stuff) , so I am kind of pulling at straws here....
Eclipse has always worked great for me....

**Comment by mauroc** [comment]
ignore this for now. Need to do more research

**Comment by rgleason** [comment]
You are not alone.  Search on [eclipse fails with legacy gdb](https://search.yahoo.com/yhs/search?showuninstallsurvey=1&installsource=direct&schemaver=1.0.0.0&year=2015&source=direct&machinelocation=244&cmpgn=rapha&hsimp=yhs-ext_onb&ssdcat=321&vendor=none&vendorsrc=firefox&oslocale=iso:usa&osvers=10.0&ver=22.17.0.183&oslang=iso:eng&os=windows&templatecat=sbu_w_1000_5039_n360dsp_esd&chn=1000&version=22.17.0.183&o=ds&p=eclipse%20fails%20with%20legacy%20gdb,%20&prt=ngc&schemacat=sbu_w&olpchannel=sesd&tpr=111&doa=2019-04-20&guid=a7b8902f-64c0-4d23-8ee8-c33b853e70d3&hspart=symantec&installstatus=updated&doi=2019-04-20&type=ff_ds_rapha_wk16_2019&param1=a7b8902f-64c0-4d23-8ee8-c33b853e70d3_2019-04-20_ff&param2=ds_direct_rapha&param3=ngc_22.17.0.183_wk16_2019&param4=1000)
