### ISSUE TITLE
Question about PR format - JG's PR changes

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#80]
I want to get this PR right.

This PR was to include Jon Gough's changes other than the  flatpak ones that did not build.
However I see that the potential PR to mauro's master shows commits on Oct 12 (leamas-reset35), Oct 19 (Merge branch "mauroc:master")  and Oct 22 (Merge branch "mauroc:master"). See
https://github.com/mauroc/squiddio_pi/compare/master...rgleason:master

The result looks OK to me and it does build with green checks but correctly fails upload to Jon's cloudsmith because I don't have credentials (its the master branch).

Is this ok to make a PR, or should I from my local repository, git pull upstream master (which is mauroc:master) --force
and then push --force that up to rgleason:master  and then rewrite the two changes?

Then make the PR?

**Comment by leamas** [comment]
You should first checkout a feature branch (call it whatever you like)
    
    $ git checkout  -b jon-fixes

The, rebase it against current upstream:
   
    $ git remote add upstream https://github.com/mauroc/squiddio_pi.git
    $ git remote update upstream
    $ git rebase upstream/master

The last command will most likely generate conflicts which you have to resolve. After doing that, push your branch to your own repo:

    $ git push --set-upstream origin jon-fixes

And then, in the github gui, create the pull request. Don't forget to inform Jon so he can review it.

**Comment by rgleason** [comment]
NOTES: While making this PR after A. Leamas set of git commands (noted above) 

It looks pretty much the same as the one before, and the changes are the same too.
https://github.com/mauroc/squiddio_pi/compare/master...rgleason:master

```
The four travis cloudsmith deploys failed again due to 
Checking raw package upload parameters ... -/|ERROR
Failed to validate upload parameters! (status: 403 - Forbidden)

Detail: You do not have permission to perform this action.
Exited with code 147
```
However I will make the PR and hope that it corrects itself in Mauro's repository.  I learned some new things that will be helpful.  Thanks

**Comment by rgleason** [comment]
Everything passed except  travis clang osx which takes longer.
