### ISSUE TITLE
PR #83 - stable versions testing

### ISSUE THREAD

**Issue by mauroc** [mauroc/squiddio_pi#84]
the unstable packages were all deployed correctly from circleci and appveyor for an untagged release

The stable packages did not deploy to squiddio-stable. The process I followed in this case was:

```
# updated version to 1.0.17.3 in Cmakelists.txt
git commit -am 'v 1.0.17.3'
git tag v1.0.17.3
git log # showed latest commit is tagged correctly as v1.0.17.3
git push origin v1.0.17.3 # this one did not trigger the circleci builds. Only appveyor
git push origin master # this one triggered all the builds, but none were deployed to squiddio-stable
```

what am I doing wrong? I feel we are so close....

**Comment by rgleason** [comment]
Maybe you put the tag in the ci/circleci-uploads.sh ?

**Comment by mauroc** [comment]
I didn't and would not know where in that file they would go. 
The issue also affects the appveyor build, not just circleci

**Comment by rgleason** [comment]
This should work, provided you issue it quickly enough.
The problem is appveyor builds quite quickly.
So maybe make the tag before pushing the commit.
git tag v1.0.19.1
Then push
git push origin v1.0.19.1

I've had appveyor complete before I did the git push origin v1.0.19.1
and there is no file pushed, it just stops.

Don't know about the circleci / cloudsmith

**Comment by rgleason** [comment]
https://stackoverflow.com/questions/30817760/circleci-how-to-deploy-depending-on-git-tag


This is Kim from CircleCI.

To archive what you want to do, I think you must be able to trigger a build when a new tag is pushed to Github. However, only a new commit will trigger a build, so it seems this is not doable as of now. Sorry!

UPDATE: This feature has now been implemented: https://circleci.com/docs/configuration/#tags

**Comment by rgleason** [comment]
https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag

**Comment by leamas** [comment]
You missed `git push --tags`. Without the --tags option the tag is not visible in the github account.

**Comment by leamas** [comment]
BTW: The links provided by @rgleason  are not relevant, we are not using this kind of functionality.

**Comment by rgleason** [comment]
Alec That is not correct they are visible without the tags option. I've been using it this way and they are clearly visible in the Tags tab under Releases.

**Comment by leamas** [comment]
This issue is about the cloudsmith deployment of installer artifacts, nothing else. They have never been available on github.

**Comment by rgleason** [comment]
Alec the tags are readily accessiblely on github, under the Releases tab there are two additional tabs one titled TAGS. To push a tag to that location I've never had to use the --tag.

**Comment by rgleason** [comment]
Maybe cloudsmith needs git authorization to see the git tags as they are added?

Strange because I thought my files were being deployed. Its up to 25mb now.

**Comment by leamas** [comment]
Could you please stick to the subject? Which is problems deploying the installer artifacts on cloudsmith. Full stop. 

Yes, tags are of course visible on github. But it has nothing to do with the subject.

**Comment by leamas** [comment]
Going back to the problem, we have the following log building c4d5cf6


    ++ git rev-parse --short=7 HEAD
    + commit=c4d5cf6
    ++ git tag --contains HEAD
    + tag= 
   
The log means that there is not tag visible which points to c4d5cf6. This might be because the tag isn't pushed -- according to initial logs it isn't. It could also be because while it exists it doesn't match c4d5cf6 i. e. there was a commit after the tagged one.

**Comment by leamas** [comment]
@rgleason: You could also just check the tags available in the github interface (tags, not releases!). V1.0.17.3 is not there.  Could we now stop this confused discussion?

**Comment by rgleason** [comment]
After my post you wrote:

- You missed git push --tags. Without the --tags option the tag is not visible in the github account.

**Comment by rgleason** [comment]
Maybe mauro waited to long to push the tag?  I think I have had that issue and had to remove the remote tag and start over.

**Comment by mauroc** [comment]
I wrote the following to myself. I don't deploy new releases very often, so I am sure the next time I will have forgotten most of the process. 
I thought it may be useful for our online docs, as an intro to a more technical step-by-step.
It would also be useful to include guidelines for the PA (plugin admin) in terms of 
- keeping their repos clean of old artifacts
- what belongs in the stable release? I.e. major releases? Minor releases? Patches? etc. 
----------------------------------------
CONTINUOUS INTEGRATION for Plugins
We use 2 CI services:
-Appveyor (Windows only)
- Circle CI (all others)
...and one 'hosting service' for executables:
- Cloudsmith
I have created accounts on all 3 using github oauth. (will each plugin admin need to do this?)
The CI cycle is automatically triggered on both CI services by a git push to github . 
The CI services are essentially notified by github through a callback that a new version is available, and they pull the code and compile it in a temporary VM, which is then destroyed after the deploy.
Note that only push'es to the master branch trigger the build!
At the end of the CI cycle, the artifacts get uploaded to Cloudsmith if the builds are successful
There are 2 repositories on Cloudsmith
- mauro-calvi/squiddio_pi: 
-- ALL builds get deployed here, if successful. Each cycle currently generates 10 artifacts (5 platforms: mingw, macos, debian , windows and flatpack. Each platform has 2 packages: one executable and one xml file used by the installer). This repo needs to be cleaned of old artifacts periodically
- mauro-calvi/squiddio-stable: 
-- this only contains the official production releases (probably only the last 2-3, to keep clutter at a minimum). Upload to this repository is triggered if and only if: 
---the latest commit has a tag associated with it , use e.g. 
git tag v1.0.17 to tag the HEAD commit
---it is pushed with the --tags option, e.g. 
git push --tags origin master

**Comment by leamas** [comment]
> This repo needs to be cleaned of old artifacts periodically

There is actually a retention policy setting for the cloudsmith repo you could set to just keep the last say 30 packages or so.

**Comment by rgleason** [comment]
I thought that for free opensource, retention policy is automatic.

**Comment by leamas** [comment]
Nope. You can find the Retention Rules settings in the left pane after pushing the Set Me Up button in the cloudsmith repo.
