### ISSUE TITLE
Question: Cloudsmith deployment - multiple plugins

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#87]
@leamas  
I understand that there will be multiple cloudsmith repositories for plugins based upon the plugin maintainers accounts.   For multiple plugins in a given cloudsmith account, should each plugin have its own cloudsmith repository (for consistency)?

**Comment by leamas** [comment]
Why? From my perspective, it's up to the repo maintainer. I cannot see any strong reasons besides possibly for the manual packages (to make it easier to browse).

**Comment by rgleason** [comment]
Ok Thanks.
