### ISSUE TITLE
How to push deployment of squiddio-manual?

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#90]
I would appreciate a summary of actions needed and how to push files up to these three locations

- squiddio_pi
- squiddio-stable
- squiddio-manual

What setup and commands mauro would execute.

**Comment by leamas** [comment]
We cannot really go into this before resolviong #71, right? Se we don't know *what* to deploy *where* I don's see the point raising the question  *how*.

**Comment by rgleason** [comment]
Yes, agreed.  We'll save it for later. Just anticipating what needs to be known.

**Comment by rgleason** [comment]
If the squiddio-stable filenames had  the "exe" file with an "ov50", you could use that same directory for both manual and stable files, thus simplifying things.

**Comment by leamas** [comment]
Perhaps we could close this issue and instead have these discussions in #71 instead?

**Comment by rgleason** [comment]
OK, I thought you wanted it separate. Closing
