### ISSUE TITLE
Option: Use Github Actions - code, build, test, publish (macOS, Linux, Windows)

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#93]
...GitHub Actions and GitHub Package Registry beta programs. .. GitHub Actions and GitHub Package Registry will be moving to general availability on November 13.

[GitHub Actions](https://github.com/features/actions)   ...these services will still be free for open source and include free quantities,

view Actions pricing here, (Linux, MacOS & Windows)   Free all public repositories

"With GitHub Actions, we are able to code, build, test and publish ImageMagick for Linux, macOS, and Windows in a single location without configuring multiple external dependencies. This is a game changer!” Dirk Lemstra ImageMagick maintainer

**Comment by leamas** [comment]
Perhaps we could close this one, and discuss if/how to use these actions in #94?

**Comment by rgleason** [comment]
Ok, no problem.
