### ISSUE TITLE
Missing build strategy.

### ISSUE THREAD

**Issue by leamas** [mauroc/squiddio_pi#94]
As of #71 we have  now decided where to store build artifacts. Next step is to define how to build them. In the short perspective, this is about using either circleci or travis for non-windows builds (keeping appveyor for the windows builds).

In a longer perspective we need to evaluate using github actions (#93). This is much more work, and we probably cannot move to using this until we have cleaned up the travis/circleci mess.

So, in the short perspective: travis or circleci? Both works. I'm personally fond of circleci, but no big deal.

Thoughts?

**Comment by rgleason** [comment]
I favor Circleci, why?
1. Tokens and encryption is easier, particularly for Win Dev.
2. Circleci seems quite fast, although I have been impressed by Travis too and I like their screens
3. Circleci information menus are good example https://circleci.com/gh/rgleason/squiddio_pi/140

**Comment by leamas** [comment]
After merging #99 the the only builders used is appveyor (windows) and circleci (all other). Case closed.
