### ISSUE TITLE
Trying Github Actions

### ISSUE THREAD

**Issue by rgleason** [mauroc/squiddio_pi#95]
https://github.com/rgleason/squiddio_pi/runs/282583159

https://github.com/rgleason/squiddio_pi/edit/rgleason-patch-1/.github/workflows/cmake.yml

**Comment by rgleason** [comment]
Have been trying to get the env variables and path set for wxwidgets in order to convert the appveyor script.   No success.

**Comment by leamas** [comment]
BTW: seems that gitlab has the same services available. Havn't looked into it. 

There are many players out there...

**Comment by rgleason** [comment]
Thanks. now trying to learn enough so that I can actually use it.  There are so many ways and tools that it will be awhile before I succeed.
